// Mock Apollo data for testing when you don't have Professional plan
// Remove this file once you have Apollo Professional trial

export const MOCK_PEOPLE = [
  {
    id: 'mock-1',
    first_name: 'Sarah',
    last_name: 'Chen',
    name: 'Sarah Chen',
    linkedin_url: 'https://linkedin.com/in/sarah-chen-example',
    title: 'Chief Technology Officer',
    email: 'sarah.chen@techcorp.com',
    organization: {
      name: 'TechCorp Solutions',
      website_url: 'https://techcorp.com',
      industry: 'Computer Software',
      num_employees: 250,
    },
    city: 'San Francisco',
    state: 'California',
    country: 'United States',
  },
  {
    id: 'mock-2',
    first_name: 'Michael',
    last_name: 'Rodriguez',
    name: 'Michael Rodriguez',
    linkedin_url: 'https://linkedin.com/in/michael-rodriguez-example',
    title: 'VP of Engineering',
    email: 'michael.r@innovateai.com',
    organization: {
      name: 'InnovateAI',
      website_url: 'https://innovateai.com',
      industry: 'Artificial Intelligence',
      num_employees: 150,
    },
    city: 'Austin',
    state: 'Texas',
    country: 'United States',
  },
  {
    id: 'mock-3',
    first_name: 'Emily',
    last_name: 'Thompson',
    name: 'Emily Thompson',
    linkedin_url: 'https://linkedin.com/in/emily-thompson-example',
    title: 'Head of Product',
    email: 'emily.t@fintech-startup.com',
    organization: {
      name: 'FinTech Startup Inc',
      website_url: 'https://fintech-startup.com',
      industry: 'Financial Technology',
      num_employees: 75,
    },
    city: 'New York',
    state: 'New York',
    country: 'United States',
  },
  {
    id: 'mock-4',
    first_name: 'David',
    last_name: 'Kim',
    name: 'David Kim',
    linkedin_url: 'https://linkedin.com/in/david-kim-example',
    title: 'Director of Engineering',
    email: 'david.kim@cloudservices.com',
    organization: {
      name: 'Cloud Services Co',
      website_url: 'https://cloudservices.com',
      industry: 'Cloud Computing',
      num_employees: 500,
    },
    city: 'Seattle',
    state: 'Washington',
    country: 'United States',
  },
  {
    id: 'mock-5',
    first_name: 'Jessica',
    last_name: 'Martinez',
    name: 'Jessica Martinez',
    linkedin_url: 'https://linkedin.com/in/jessica-martinez-example',
    title: 'Chief Operating Officer',
    email: 'j.martinez@healthcare-tech.com',
    organization: {
      name: 'Healthcare Tech Solutions',
      website_url: 'https://healthcare-tech.com',
      industry: 'Healthcare Technology',
      num_employees: 300,
    },
    city: 'Boston',
    state: 'Massachusetts',
    country: 'United States',
  },
  {
    id: 'mock-6',
    first_name: 'Alex',
    last_name: 'Patel',
    name: 'Alex Patel',
    linkedin_url: 'https://linkedin.com/in/alex-patel-example',
    title: 'VP of Product',
    email: 'alex.patel@saas-platform.com',
    organization: {
      name: 'SaaS Platform Inc',
      website_url: 'https://saas-platform.com',
      industry: 'SaaS',
      num_employees: 180,
    },
    city: 'San Francisco',
    state: 'California',
    country: 'United States',
  },
  {
    id: 'mock-7',
    first_name: 'Rachel',
    last_name: 'Foster',
    name: 'Rachel Foster',
    linkedin_url: 'https://linkedin.com/in/rachel-foster-example',
    title: 'Senior Engineering Manager',
    email: 'rachel.f@dataanalytics.com',
    organization: {
      name: 'Data Analytics Corp',
      website_url: 'https://dataanalytics.com',
      industry: 'Data & Analytics',
      num_employees: 120,
    },
    city: 'Chicago',
    state: 'Illinois',
    country: 'United States',
  },
  {
    id: 'mock-8',
    first_name: 'James',
    last_name: 'Wilson',
    name: 'James Wilson',
    linkedin_url: 'https://linkedin.com/in/james-wilson-example',
    title: 'CTO',
    email: 'james.wilson@enterprise-software.com',
    organization: {
      name: 'Enterprise Software Ltd',
      website_url: 'https://enterprise-software.com',
      industry: 'Enterprise Software',
      num_employees: 450,
    },
    city: 'Denver',
    state: 'Colorado',
    country: 'United States',
  },
];

export function getMockSearchResults() {
  return {
    people: MOCK_PEOPLE,
    pagination: {
      page: 1,
      per_page: 10,
      total_entries: MOCK_PEOPLE.length,
      total_pages: 1,
    },
  };
}

